### ISSUE TITLE
Overlap with ReactJS.NET?

### ISSUE THREAD

**Issue by Daniel15** [aspnet/NodeServices#21] opened 2015-12-09 18:20 UTC
Hello!

I just found out about this project today. I work on a project called [ReactJS.NET](http://reactjs.net/) that handles compiling JSX files to JavaScript (via Babel), and server-side rendering of React components, both in ASP.NET 4 and 5. It seems like there'd be quite a bit of overlap between what ReactJS.NET provides and what `Microsoft.AspNet.ReactServices` provides. What are the advantages that `ReactServices` would provide over ReactJS.NET? :smiley: 

Currently with ReactJS.NET I'm using V8 and falling back to Chakra (via [JavaScriptEngineSwitcher](https://github.com/Taritsyn/JavaScriptEngineSwitcher)) but I've considered adding support for Node.js too. Have you seen any issues with using Node.js from ASP.NET?

**Comment by SteveSandersonMS** [comment] 2015-12-10 20:44
Hey, thanks for getting in touch.

The underlying NodeServices package gives us a platform on which we can build support for all kinds of server-side JavaScript libraries and frameworks in ASP.NET, in a cross-platform, CoreCLR-compatible way. It's natural and easy to plug in things like Angular2 and React, hence those packages. Supporting server-side rendering is just one of many things we'll do - other features that may go into AngularServices/ReactServices/etc would be server-client interop for features like routing and validation.

I'd be very interested to know if, in your experience of working in this area, there are other React+ASP.NET interoperability features you think we should add (either on the server in ASP.NET itself, or as client-side functionality)!

> Have you seen any issues with using Node.js from ASP.NET?

So far it's looking great. When Edge.js gets CoreCLR support I'll look into adding that as a hosting/transport option in case it improves perf.

I'll mark this as closed as it's not a bug or feature request, but please feel free to continue the conversation :)

**Closed by SteveSandersonMS** 2015-12-10 20:44 UTC

**Comment by Daniel15** [comment] 2015-12-11 06:15
> I'd be very interested to know if, in your experience of working in this area, there are other React+ASP.NET interoperability features you think we should add (either on the server in ASP.NET itself, or as client-side functionality)!

Support for JavaScript-based routing (eg. React-router) is a common request, I haven't quite worked out the best way to support it though. It sounds like that's something you're thinking about too though, which is great!

Flux architecture is another big thing I haven't really thought about in terms of server-side rendering. If a React component reads data from a Flux store and uses that to render, how would the Flux stores be populated server-side and how would that be rendered server-side? I've seen a few attempts at doing this with Node.js servers, but I haven't seen any good non-Node.js ways of handling it.

In ReactJS.NET I have a handler to compile JSX on the fly via Babel (using a handler for ASP.NET 4 and middleware for ASP.NET 5). It's been quite useful in the past, but I guess it's not that important these days now that systems like Webpack and Browserify are so common. Back when I built the original version of ReactJS.NET, Webpack and Browserify weren't really popular in the .NET ecosystem :)

**Comment by andersekdahl** [comment] 2015-12-12 18:49
Something to think about is that it's not recommended to import `react` straight from Node.js. This becuase the React code base is filled with checks against `process.env.NODE_ENV` and those are expensive enough to make a difference. 

The recommended way is to instead build a special bundle  for the server rendering where all those checks are removed by Uglify. So for server rendering with React you just need a JavaScript engine, the Node.js API/runtime isn't really needed.

**Comment by Daniel15** [comment] 2015-12-12 19:51
>  it's not recommended to import react straight from Node.js

I don't think that's really true; lots of people are using server-side React rendering in Node.js :smile: 

> This becuase the React code base is filled with checks against process.env.NODE_ENV and those are expensive enough to make a difference.

So set `NODE_ENV` to `production` when running Node.js, it's just an environment variable. A Node.js instance running in production should already have `NODE_ENV` set this way.

> The recommended way is to instead build a special bundle for the server rendering where all those checks are removed by Uglify. 

For what it's worth, this is what I do with ReactJS.NET for the React version I bundle with it: https://github.com/reactjs/React.NET/blob/master/src/React.Core/gulpfile.js#L61

>  So for server rendering with React you just need a JavaScript engine, the Node.js API/runtime isn't really needed.

I'm using V8 and Chakra directly with ReactJS.NET, which mostly works but it makes it pretty much impossible to use Node.js modules directly (without compiling them via Webpack or Browserify). Using Node.js has the advantage that it's super easy to use other scripts from the Node.js ecosystem.

**Comment by andersekdahl** [comment] 2015-12-12 19:59
What I meant was that you should import the minified `react` on the server instead of just `import React from 'react'`. Lots of people are using server rendering in Node.js, never meant to imply anything else. But you get around 30% performance penalty for not bundling or using the minified version directly.

`process.env.NODE_ENV` is just a an environment variable, but the `process` object is not just a regular object. So if you call it enough times, the cost starts to show, which is the case for React.

https://github.com/facebook/react/issues/812

**Comment by Daniel15** [comment] 2015-12-12 22:05
> process.env.NODE_ENV is just a an environment variable, but the process object is not just a regular object. So if you call it enough times, the cost starts to show, which is the case for React.

Ahhh, interesting. I thought Node would cache it, but I guess not. That's unfortunate.
